# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 15ca23951096e078c7eff40dbfac4360f26a8cf3224db4ce52642d4611f4ac2b6556999b3a719c3e31f4f3dbec4c9eaf635ab160c32e92e38bfdba6985c45132

test:
  secret_key_base: 4bb4828532d31f06f0e67aab7e2a45d9017c4f40fa47fa1081d5b62a255a854d08f1327b1b42180af4b0f6b563af02839ff702101f6a01c1b6fc861c5bdd9c8d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
